### PR TITLE
Update to most core

### PR DESCRIPTION
**Pull request by briancavalier**
Update examples to `@most/core`, rollup + babel 7 build, pipeline operator and most-product in type-to-search.

The pipeline operator is quite nice with `@most/core`.  I could have used it everywhere, but that felt a little optimistic since it's still a proposal.  So, I decided just to use it in one example.

### CODE REVIEW

**Review by davidchase — APPROVED** [review]
LGTM

**Comment by davidchase** [comment]
the only thing i wonder is if everyone who comes along to these examples gets the gist with something like `|>` maybe its pretty obvious

**Comment by briancavalier** [comment]
I'll add a note about it.

**Comment by briancavalier** [comment]
@davidchase See 09b11e9

**Comment by davidchase** [comment]
👌

**Pull request merged**
