### PR TITLE
Add mouse-position example

### PR DESCRIPTION
**Pull request by briancavalier**
I refactored it to use functional API instead of fluent.  There are a million ways to format this tiny example, so wondering what is best to show.  Thoughts?

A couple variations for comparison.  Fluent:

``` js
import { mousemove } from '@most/dom-event'

const toCoords = e => `${e.clientX},${e.clientY}`
const render = s => { document.body.textContent = s }

mousemove(document)
  .map(toCoords)
  .startWith('move the mouse, please')
  .observe(render)
```

Another functional variant:

``` js
import { map, startWith, observe } from 'most'
import { mousemove } from '@most/dom-event'

const toCoords = e => `${e.clientX},${e.clientY}`
const render = s => { document.body.textContent = s }

const coords = startWith('move the mouse, please', map(toCoords, mousemove(document)))

observe(render, coords)
```

### CODE REVIEW

**Comment by davidchase** [comment]
`mouse-position/index.js`

``` js
/*
* Typically we have a fluent api
*
* import { mousemove } from '@most/dom-event'
*
* const toCoords = e => `${e.clientX},${e.clientY}`
* const render = s => { document.body.textContent = s }
*
* mousemove(document)
*  .map(toCoords)
*  .startWith('move the mouse, please')
*  .observe(render)
*
*/

// But with functions it becomes more elegant
import { map, startWith, observe } from 'most'
import { mousemove } from '@most/dom-event'

const toCoords = e => `${e.clientX},${e.clientY}`
const render = s => { document.body.textContent = s }

const coords = map(toCoords, mousemove(document))

observe(render, startWith('move the mouse, please', coords))
```

**Comment by briancavalier** [comment]
I like that idea.  What do you think of flipping them around?  E.g. like this:

``` js
import { map, startWith, observe } from 'most'
import { mousemove } from '@most/dom-event'

const toCoords = e => `${e.clientX},${e.clientY}`
const render = s => { document.body.textContent = s }

const coords = map(toCoords, mousemove(document))

observe(render, startWith('move the mouse, please', coords))

/*
* The same can be done with a fluent API
*
* import { mousemove } from '@most/dom-event'
*
* const toCoords = e => `${e.clientX},${e.clientY}`
* const render = s => { document.body.textContent = s }
*
* mousemove(document)
*  .map(toCoords)
*  .startWith('move the mouse, please')
*  .observe(render)
*
*/
```

**Comment by davidchase** [comment]
Whatever works I was thinking show old then new but I don't think it matters too much :P

**Comment by briancavalier** [comment]
Rebased and added commented-out fluent example.  I think this is ready to merge (finally!)

**Comment by davidchase** [comment]
:shipit:

**Pull request merged**
