### PR TITLE
Add a root index.html

### PR DESCRIPTION
**Pull request by johnrees**
Setting the master branch to be hosted with github pages in /settings

screen shot 2017-07-04 at 14 59 15

would enable users to test the examples without cloning the directory at https://mostjs.github.io/examples/

e.g. https://johnrees.github.io/examples

### CODE REVIEW

**Comment by johnrees** [comment]
Although the wikipedia example won't work when hosted because it's an insecure request. After fixing that it will fail again because of its CORS policy.

**Comment by briancavalier** [comment]
Thanks @johnrees, this is a good idea :+1:

The wikipedia request is a GET (not a POST) using `jsonp`.  That should work cross-origin, right?  If so, then I think we can merge this.  If it won't work for some reason, then we'll need to figure out what to do.

**Comment by johnrees** [comment]
Ah yes, you're correct. I've tested it and it works

**Comment by briancavalier** [comment]
This is great.  Thanks again @johnrees!

I enabled gh-pages on master: https://mostjs.github.io/examples/

**Pull request merged**
